version: '3.1'
services:

  fiap-hackathon-booking-grupo12:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/fiap-hackathon-booking-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

networks:
  intranet:
    driver: bridge